name: Feature Request
description: Feature a request for Respect Funkin here!
labels: [enhancement]
body:
  - type: textarea
    attributes:
      label: What feature do you want to get added on the **base** game?
    validations:
      required: true